### ISSUE TITLE
Addon under 2.93 still broken

### ISSUE THREAD

**Issue by Surody** [leomoon-studios/leomoon-lightstudio#42]
Trying to install the addon with the 2.93 hotfix still causes a error to occur when I try to install it. When I restart Blender after trying to install it, it's activatable and works but after restarting Blender again the addon is still activated but doesn't function.

**Comment by leomoon** [comment]
We're working on a fix. there's something strange going with registering in Blender 2.93+.

**Comment by Prototype-Zer0** [comment]
I am digging through this as well, I thought I was able to fix the issue but that was due to me registering the profile_list manually, the main error I'm seeing on initial installation is 
`Traceback (most recent call last):
  File "/app/blender/2.93/scripts/modules/addon_utils.py", line 386, in enable
    mod.register()
  File "/home/prototype/.var/app/org.blender.Blender/config/blender/2.93/scripts/addons/leomoon-lightstudio-master/__init__.py", line 32, in register
    auto_load.register()
  File "/home/prototype/.var/app/org.blender.Blender/config/blender/2.93/scripts/addons/leomoon-lightstudio-master/auto_load.py", line 42, in register
    bpy.utils.register_class(cls)
ValueError: bpy_struct "LeoMoon_Light_Studio_Properties" registration error: profile_list could not register
`
Currently digging through the API changes to see if they changed something about the way classes are being registered... You can make the script work by registering the class manually but that is not viable for the majority of users.

**Comment by leomoon** [comment]
I have the same problem. It's not clear why it works sometimes.

**Comment by Prototype-Zer0** [comment]
So it's getting pretty ridiculous and way too random, I got to work semi successfully on my Linux machine by inserting the following line before the full registration in light_list.py:
`bpy.utils.register_class(LightListItem)` 
This is forcing the class to be registered regardless, another way I think might work is to force register the entire module but I have not tested that yet, anyway the issue still presists on other machines I have tested on so I will keep you posted if I can 100% stop this error from occurring.

**Comment by leomoon** [comment]
This issue should be fixed with LightStudio version 2.8.1:
https://github.com/leomoon-studios/leomoon-lightstudio/archive/refs/heads/master.zip
